Algoritmo "6ENQUANTO1A5SOMA"

Var
// Seção de Declaração de Variáveis
   num1, num2: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
   Escreval("Digite o primeiro número:")
   Leia(num1)
   Escreval("Digite o segundo número:")
   Leia(num2)
   Se (num1 > num2) Então
      Escreval("O primeiro número é maior")
   Senão
      Escreval("O segundo número é maior")
   Fimse
   
Fimalgoritmo